# Generated by Django 6.0.2 on 2026-02-22 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0003_alter_market_updated_at'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_markets',
            field=models.ManyToManyField(blank=True, related_name='allowed_farmers', to='markets.market'),
        ),
    ]
