# Generated by Django 6.0.3 on 2026-04-05 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_allowed_markets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='allowed_markets',
        ),
    ]
