# Generated by Django 6.0.2 on 2026-02-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_market_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
